# Generated by Django 5.2 on 2025-04-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=200)),
                ("mini_description", models.TextField()),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("processor", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=100)),
                ("disk", models.CharField(max_length=100)),
                ("internet_speed", models.CharField(max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="backend_api.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики услуг",
                "verbose_name_plural": "Характетистики услуги",
                "ordering": ["id"],
            },
        ),
    ]
