# Generated by Django 5.2 on 2025-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
