# Generated by Django 5.2 on 2025-04-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0002_remove_service_description_alter_service_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicespecification",
            options={
                "ordering": ["id"],
                "verbose_name": "Характеристика услуги",
                "verbose_name_plural": "Характетистики услуг",
            },
        ),
    ]
